make:
	verilator -sv --timing --trace --binary --top-module testbench src/single_cycle_top.sv src/mux2.sv src/adder.sv src/branch_unit.sv src/pc.sv src/instr_mem.sv src/regfile.sv src/imm_gen.sv src/alu.sv src/data_mem.sv src/control_unit.sv src/testbench.sv src/instr_parser.sv
